### ISSUE TITLE
undefined filename issue with bindings module when used with webpack-dev-server

### ISSUE THREAD

**Issue by glawson** [codebytere/node-mac-permissions#2]
When using with webpack and webpack-dev-server, I ran into:

```
[18:16:53] [webpack-dev-server] http://localhost:8083
App threw an error during load
TypeError: Cannot read property 'indexOf' of undefined
    at Function.getFileName (webpack-internal:///./node_modules/bindings/bindings.js:178:16)
```

TLDR is when packaging for the dev-server, the bindings module used to find the permissions.node file errors with the above.  

**Quick workaround**; in the webpack config for the main.js file, include:

```
externals: [
    (() => {
      const IGNORES = [
         'node-mac-permissions',
      ];

      return (context, request, callback) => {
        if (IGNORES.indexOf(request) >= 0) {
          return callback(null, `require('${request}')`);
        }

        return callback();
      };
    })(),
  ]
```

ref: https://github.com/railsware/bozon/issues/40#issuecomment-287992554

**Comment by codebytere** [comment]
@glawson to my current knowledge, getting this error means that webpack packed this module, which it should not. I'm pretty sure if you just configure webpack to use this module externally (e.g explicitly don't pack it), & the problem should be resolved & the low level binding will work.

**Comment by glawson** [comment]
@codebytere  - exactly.  Just wanted to make mention of it in case anyone else runs into this error.

**Comment by codebytere** [comment]
Added a note to the README - thanks for the heads up!

**Comment by mmaietta** [comment]
Just chiming in and potentially resurrecting an old issue. If using es6 imports:
```
import * as NodeMacPermissions from "node-mac-permissions";
```
The externals setup can be simplified to:
```
externals: [{
    'permissions': 'node-mac-permissions'
}]
```

**Comment by mbruschi** [comment]
@mmaietta FYI I tried it out with the es6 import but still get the initial error mentioned here: `Cannot read property 'indexOf' of undefined`. Happy to provide more details but right now don't know what could be useful.

**Comment by mmaietta** [comment]
@mbruschi here is my up-to-date webpack config with relevant sections below. Hope that helps!
```
{
    test: /\.js$/,
    // Finds node addons in build/Release and node_modules
    loader: "node-bindings-loader"
},
{
    test: /\.node$/,
    // Converts paths from source code and resolved paths from `node-bindings-loader` to use __dirname or process.execPath
    loader: "awesome-node-loader",
    options: {
        useDirname: !packDistributable
    }
},
```
```
externals: packDistributable ? [ 'permissions', 'electron-deeplink.node' ] : [nodeExternals()],
```
